# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db53305ab7c27d1fadcc061eac212e42db80ec4390105221ccf8f70825d32b2c47ce4ae9b158912c631d7d2fa2623e8bec91c9ee40ee0c816ecb4ccd611b77ac

test:
  secret_key_base: 306b50a3e937c2afa2c83544d166aa8f3dd7353ca55abe6175dd050df8ca8ae82a590e9a677eb4907d64cc3cd060a19c7f5a4338eaf0266e6778f84a8218a2c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
